# Generated by Django 3.0.3 on 2020-02-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testspatial', '0002_worldborder_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='region',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='worldborder',
            name='un',
        ),
    ]
